apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: geoip-https-hpa
  namespace: osg-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: geoip-https
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Object
    object:
      metric:
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        name: geoip-https-ing
      target:
        type: Value
        value: 5k
